### ISSUE TITLE
Why does denoising now work for GRDH imagery?

### ISSUE THREAD

**Issue by ashnair1** [nansencenter/sentinel1denoised#80]
I have a Sentinel 1 archive named (`S1B_EW_GRDH_1SDH_20190820T075249_20190820T075349_017666_0213C3_F0A9.zip`) that I wanted to denoise. However this fails with the following error:

```
10:07:37|40|nansat|_get_dataset_metadata|GDAL could not open ./S1B_EW_GRDH_1SDH_20190820T075249_20190820T075349_017666_0213C3_F0A9.zip, trying to read with Nansat mappers...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/s1denoise-1.2-py3.7.egg/s1denoise/sentinel1image.py", line 35, in __init__
    raise ValueError( 'Source file must be Sentinel-1A/1B '
ValueError: Source file must be Sentinel-1A/1B IW_GRDH_1SDH, IW_GRDH_1SDV, EW_GRDM_1SDH, or EW_GRDM_1SDV product.
```

Is this because the file is in high resolution (GRDH) instead of medium resolution (GRDM)? IW and EW can have medium or high resolution. But according to the error message, denoising is only possible for high resolution IW GRD images and medium resolution EW GRD images. Why is this the case?

Full disclosure: I'm new to SAR image processing so if there's any obvious mistake in my question, kindly let me know

**Comment by xdenisx** [comment]
Hi ashnair1!

I looked through the `denoising_parameters.json` file and found we don't have trained denoisng parameters for EW GRDH mode so to make the algorithm applicable for the data you need to perform a training first. Try to follow our guidelines here `https://github.com/nansencenter/sentinel1denoised/tree/master/training` and let us know if something goes wrong. Good luck!
