### ISSUE TITLE
Error whn trying to run s1_correction.py

### ISSUE THREAD

**Issue by hiredgoon8118** [nansencenter/sentinel1denoised#88]
Environment set up no problem...

But similar problem to the other open issues when trying to run...

s1_correction.py  S1A_EW_GRDM_1SDH_20211129T235741_20211129T235841_040793_04D7A6_8F09.zip  Test.tif
08:17:22|40|nansat|_get_dataset_metadata|GDAL could not open S1A_EW_GRDM_1SDH_20211129T235741_20211129T235841_040793_04D7A6_8F09.zip, trying to read with Nansat mappers...
Traceback (most recent call last):
  File "/data/data275/pub/RESEARCH/SOFTWARE/anaconda3/envs/s1denoise/bin/s1_correction.py", line 19, in <module>
    s1 = run_correction(args.ifile)
  File "/data/data275/pub/RESEARCH/SOFTWARE/anaconda3/envs/s1denoise/lib/python3.9/site-packages/s1denoise/tools.py", line 46, in run_correction
    s1 = Sentinel1Image(ifile)
  File "/data/data275/pub/RESEARCH/SOFTWARE/anaconda3/envs/s1denoise/lib/python3.9/site-packages/s1denoise/sentinel1image.py", line 113, in __init__
    self.download_aux_calibration(auxCalibFilename, self.platform.lower())
UnboundLocalError: local variable 'auxCalibFilename' referenced before assignment
(s1denoise) [cjackson@rhw1164 S1_Python]$

**Comment by hlkong98** [comment]
I am running into exactly the same issue! Did you find a solution yet? :)
