### ISSUE TITLE
Errors with S1B

### ISSUE THREAD

**Issue by benjaminmlucas** [nansencenter/sentinel1denoised#89]
I downloaded over 700 images and found that your package only worked on 35 of them. It doesn't seem to work with ANY s1B images at all.

The error I get is:
12:05:01|40|nansat|_get_dataset_metadata|GDAL could not open /media/benjamin/blue_benny/data/train/zip/S1B_EW_GRDM_1SDH_20190119T073624_20190119T073724_014560_01B1F4_4335.zip, trying to read with Nansat mappers...
Traceback (most recent call last):
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fccabaf3550>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='qc.sentinel1.eo.esa.int', port=443): Max retries exceeded with url: /product/S1B/AUX_CAL/20160422T000000/S1B_AUX_CAL_V20160422T000000_G20180622T074003.SAFE.TGZ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fccabaf3550>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/benjamin/Dropbox/nerd_stuff/postdoc/code/s1_denoise_autoencoder/code/main.py", line 49, in <module>
    main()
  File "/home/benjamin/Dropbox/nerd_stuff/postdoc/code/s1_denoise_autoencoder/code/main.py", line 21, in main
    train_data = Sentinel1(image_dir=args.dir, dataset="train")
  File "/home/benjamin/Dropbox/nerd_stuff/postdoc/code/s1_denoise_autoencoder/code/s1_dataset.py", line 25, in __init__
    self.train_list, self.target_list = self._get_data()
  File "/home/benjamin/Dropbox/nerd_stuff/postdoc/code/s1_denoise_autoencoder/code/s1_dataset.py", line 74, in _get_data
    self._extract_from_zip()
  File "/home/benjamin/Dropbox/nerd_stuff/postdoc/code/s1_denoise_autoencoder/code/s1_dataset.py", line 153, in _extract_from_zip
    s1 = Sentinel1Image(image_path)
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/s1denoise/sentinel1image.py", line 113, in __init__
    self.download_aux_calibration(auxCalibFilename, self.platform.lower())
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/s1denoise/sentinel1image.py", line 131, in download_aux_calibration
    r = requests.get(cal_url, stream=True)
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/benjamin/miniconda3/envs/s1denoise/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='qc.sentinel1.eo.esa.int', port=443): Max retries exceeded with url: /product/S1B/AUX_CAL/20160422T000000/S1B_AUX_CAL_V20160422T000000_G20180622T074003.SAFE.TGZ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fccabaf3550>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by avalentino** [comment]
The http://qc.sentinel1.eo.esa.int site has been discontinued.
It is supposed to be replaced by https://qc.sentinel1.copernicus.eu.

**Comment by benjaminmlucas** [comment]
I've changed that in download_aux_calibration in sentinel1image.py but it seems to still throw the error. Any idea where else it is called? Maybe in one of the Nansat classes?
