### ISSUE TITLE
Error in creating Sentine1Image object

### ISSUE THREAD

**Issue by behzad-vahedi** [nansencenter/sentinel1denoised#90]
Hi,

I've installed the latest version of the package in a new, clean conda environment and followed all the steps in the installation guide. When I try to create a Sentinel1Image object, I get the following error. Could you help me with how to fix this, please?

> from s1denoise import Sentinel1Image
> s1 = Sentinel1Image("S1B_EW_GRDM_1SDH_20181113T074529_20181113T074629_013583_019254_D382.zip")
`
03:10:51|40|nansat|_get_dataset_metadata|GDAL could not open S1B_EW_GRDM_1SDH_20181113T074529_20181113T074629_013583_019254_D382.zip, trying to read with Nansat mappers...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/s1denoise/sentinel1image.py", line 29, in __init__
    Nansat.__init__( self, filename, mapperName=mapperName, logLevel=logLevel)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/nansat/nansat.py", line 159, in __init__
    self.vrt = self._get_mapper(mapper, **kwargs)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/nansat/nansat.py", line 1164, in _get_mapper
    tmp_vrt = nansatMappers[iMapper](self.filename, gdal_dataset, metadata, **kwargs)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/nansat/mappers/mapper_sentinel1_l1.py", line 185, in __init__
    self.create_bands(metaDict)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/nansat/vrt.py", line 918, in create_bands
    self.create_band(src, dst)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/nansat/vrt.py", line 999, in create_band
    dst['name'], wkv = self._create_band_name(dst)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/nansat/vrt.py", line 698, in _create_band_name
    wkv_pti = pti.get_wkv_variable(str(wkv_dst))
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/pythesint/vocabulary.py", line 45, in find_keyword
    for d in self.get_list():
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/site-packages/pythesint/json_vocabulary.py", line 22, in get_list
    result = json.load(opened_file)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/behzad/anaconda3/envs/s1denoise/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
er.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by CatherineTaelman** [comment]
I am running into exactly the same issue! Did you find a solution yet?:)

**Comment by jlo031** [comment]
Same issue here. Any progress or ideas by anyone?

**Comment by elmioaccount** [comment]
Also here... exactly the same issue. Looking forward for a solution.

**Comment by akorosov** [comment]
Try updating pythesint pip install --update pythesint and run python -c 'import pythesint;pythesint.update_all_vocabularies()'
